# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10DNvhAJfElLT8zttxE6z7aMJU3bilq_u
"""

import streamlit as st
import pickle
import pandas as pd

# Load the trained model
with open("/content/drive/MyDrive/INTERNSHIP/NANDHINI/exercise_calories_model.pkl", "rb") as file:
    model = pickle.load(file)

st.title("🔥 Exercise Calories Predictor")
st.write("Predict calories burned based on your exercise details")

# User inputs
day = st.number_input("Enter the day", min_value=1, max_value=31, step=1)
minutes = st.number_input("Minutes exercised", min_value=0, step=5)

# Prediction button
if st.button("Predict Calories"):
    input_data = pd.DataFrame({
        "day": [day],
        "minutes_exercised": [minutes]
    })

    prediction = model.predict(input_data)

    st.success(f"Estimated calories burned: **{prediction[0]:.2f} kcal**")
